export interface CrearCitas{
    _id?: string,
    nombres: string,
    apellidos: string,
    iden: string,
    cc: string,
    nacimiento: string,
    telefono: string,
    email: string,
    departamento: string,
    especialidad: string,
    fecha: string,
    time: string,
    descripcion: string,    
}